local oil = require('oil')
local test_util = require('spec.test_util')

describe('oil select', function()
  after_each(function()
    test_util.reset_editor()
  end)

  it('opens file under cursor', function()
    test_util.oil_open()
    vim.cmd.normal({ args = { 'G' } })
    test_util.await(oil.select, 2)
    assert.equals(1, #vim.api.nvim_tabpage_list_wins(0))
    assert.not_equals('oil', vim.bo.filetype)
  end)

  it('opens file in new tab', function()
    test_util.oil_open()
    local tabpage = vim.api.nvim_get_current_tabpage()
    test_util.await(oil.select, 2, { tab = true })
    assert.equals(2, #vim.api.nvim_list_tabpages())
    assert.equals(1, #vim.api.nvim_tabpage_list_wins(0))
    assert.not_equals(tabpage, vim.api.nvim_get_current_tabpage())
  end)

  it('opens file in new split', function()
    test_util.oil_open()
    local winid = vim.api.nvim_get_current_win()
    test_util.await(oil.select, 2, { vertical = true })
    assert.equals(1, #vim.api.nvim_list_tabpages())
    assert.equals(2, #vim.api.nvim_tabpage_list_wins(0))
    assert.not_equals(winid, vim.api.nvim_get_current_win())
  end)

  it('opens multiple files in new tabs', function()
    test_util.oil_open()
    vim.api.nvim_feedkeys('Vj', 'x', true)
    local tabpage = vim.api.nvim_get_current_tabpage()
    test_util.await(oil.select, 2, { tab = true })
    assert.equals(3, #vim.api.nvim_list_tabpages())
    assert.equals(1, #vim.api.nvim_tabpage_list_wins(0))
    assert.not_equals(tabpage, vim.api.nvim_get_current_tabpage())
  end)

  it('opens multiple files in new splits', function()
    test_util.oil_open()
    vim.api.nvim_feedkeys('Vj', 'x', true)
    local winid = vim.api.nvim_get_current_win()
    test_util.await(oil.select, 2, { vertical = true })
    assert.equals(1, #vim.api.nvim_list_tabpages())
    assert.equals(3, #vim.api.nvim_tabpage_list_wins(0))
    assert.not_equals(winid, vim.api.nvim_get_current_win())
  end)

  it('remembers the directory entered when selecting a subdirectory', function()
    local test_adapter = require('oil.adapters.test')
    require('oil.config').view_options.show_hidden = true
    test_adapter.test_set('/projects/foo/bar.txt', 'file')

    test_util.actions.open({ 'oil-test:///' })
    test_util.actions.focus('projects/')
    test_util.await(oil.select, 2)
    assert.equals('oil-test:///projects/', vim.api.nvim_buf_get_name(0))

    -- Go back up via actions.parent
    oil.open()
    test_util.wait_oil_ready()
    assert.equals('oil-test:///', vim.api.nvim_buf_get_name(0))
    assert.equals('projects', oil.get_cursor_entry().name)
  end)

  it('restores cursor to the directory we came from when selecting ..', function()
    local test_adapter = require('oil.adapters.test')
    require('oil.config').view_options.show_hidden = true
    test_adapter.test_set('/projects/foo/bar.txt', 'file')
    test_adapter.test_set('/docs/readme.md', 'file')

    -- Open root and put cursor on docs (do not enter)
    test_util.actions.open({ 'oil-test:///' })
    test_util.actions.focus('docs/')
    assert.equals('docs', oil.get_cursor_entry().name)

    -- Directly open projects/ without changing root's remembered cursor
    vim.cmd.edit({ args = { 'oil-test:///projects/' } })
    test_util.wait_oil_ready()
    assert.equals('oil-test:///projects/', vim.api.nvim_buf_get_name(0))

    -- Select .. to go back to root
    test_util.actions.focus('../')
    test_util.await(oil.select, 2)

    assert.equals('oil-test:///', vim.api.nvim_buf_get_name(0))
    assert.equals('projects', oil.get_cursor_entry().name)
  end)

  describe('close after open', function()
    it('same window', function()
      vim.cmd.edit({ args = { 'foo' } })
      local bufnr = vim.api.nvim_get_current_buf()
      test_util.oil_open()
      vim.cmd.normal({ args = { 'G' } })
      test_util.await(oil.select, 2, { close = true })
      assert.equals(1, #vim.api.nvim_tabpage_list_wins(0))
      assert.not_equals(bufnr, vim.api.nvim_get_current_buf())
      assert.not_equals('oil', vim.bo.filetype)
    end)

    it('split', function()
      vim.cmd.edit({ args = { 'foo' } })
      local bufnr = vim.api.nvim_get_current_buf()
      local winid = vim.api.nvim_get_current_win()
      test_util.oil_open()
      test_util.await(oil.select, 2, { vertical = true, close = true })
      assert.equals(2, #vim.api.nvim_tabpage_list_wins(0))
      assert.equals(bufnr, vim.api.nvim_win_get_buf(winid))
    end)

    it('tab', function()
      vim.cmd.edit({ args = { 'foo' } })
      local bufnr = vim.api.nvim_get_current_buf()
      local tabpage = vim.api.nvim_get_current_tabpage()
      test_util.oil_open()
      test_util.await(oil.select, 2, { tab = true, close = true })
      assert.equals(1, #vim.api.nvim_tabpage_list_wins(0))
      assert.equals(2, #vim.api.nvim_list_tabpages())
      vim.api.nvim_set_current_tabpage(tabpage)
      assert.equals(bufnr, vim.api.nvim_get_current_buf())
    end)
  end)
end)
